# Generated by Django 5.1.6 on 2025-02-28 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_order', to='soko.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='soko.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
